### ISSUE TITLE
스터디 진행계획 결정

### ISSUE THREAD

**Issue by SooKim1110** [Effective-Java-Camp/real-my-sql#1]
Real MySQl 8.0에서 어떤 부분을 공부할지 & 주차별 분량을 어떻게 나눌지 함께 정해보면 좋을 것 같습니다.

#### < 1권 목차 >
1. 소개
2. 설치와 설정
3. 사용자 및 권한
4. 아키텍처
5. 트랜잭션과 잠금
6. 데이터 압축
7. 데이터 암호화
8. 인덱스
9. 옵티마이저와 힌트
10. 실행 계획

#### < 2권 목차 >
11. 쿼리 작성 및 최적화
12. 확장 검색
13. 파티션
14. 스토어드 프로그램
15. 데이터 타입
16. 복제
17. InnoDB 클러스터
18. Performance 스키마 & Sys 스키마

**Comment by SooKim1110** [comment]
개인적으로는 

4장. 아키텍처
5장. 트랜잭션과 잠금
8장. 인덱스
9장. 옵티마이저와 힌트
11장. 쿼리 작성 및 최적화 (1권 부터 읽기로 했지만, 정작 쿼리 작성은 2권에 있더라구요...!)
13장. 파티션

을 위주로 읽어보고 싶습니다.

**Comment by ruthetum** [comment]
## 같이 스터디하고 싶은 내용
저도 지수님과 거의 동일합니다.

**4장. 아키텍처
5장. 트랜잭션과 잠금
8장. 인덱스
9장. 옵티마이저와 힌트**
10장. 실행 계획
**11장. 쿼리 작성 및 최적화**
12장. 확장 검색
**13장. 파티션**
18장. Performance 스키마 & Sys 스키마

## 성능 최적화 관련
이번에 MySQL을 공부하면서 성능 최적화까지 같이 공부하고 싶다보니 [관련 책](https://product.kyobobook.co.kr/detail/S000061776793)의 목차도 함께 확인해봤는데요.

그래서 같이 보면 좋겠다고 생각되어 `10장. 실행 계획`, `18장. Performance 스키마 & Sys 스키마`를 추가해봤습니다.

## 검색
`12장. 확장 검색`은 저희가 예전에 데브캠프 때 검색 기능 추가하려면 Mongo를 엘라스틱서치로 덤핑해줘야 하나 등을 고민해보면서 검색에 대한 것도 고민해본 경험이 있다고 생각들어요.

다만 당시에는 이런저런 제약으로 인해 검색에 대해 많이 신경을 쓰지 못 했는데 이번 기회에 같이 공부해보고 고민해보면 좋을 것 같다는 생각이 들어요. 양이 너무 많다면 full text search 정도만 같이 보는 것도 좋을 것 같아요.

## 복제
`16장. 복제`는 따로 첨부하지 않았는데요.

복제는 이번 기회에 같이 봐도 좋고, 각자 봐도 좋을 것 같아요. 사실 아직까지는 replication을 이용하고 있구나 정도만 알 고 있고, 어떤 형태로 작동되는지 모르다보니 함께 공부해보거나 각자의 상황에서 사용되는 예를 공유해보면서 같이 고민해보면 재밌을 것 같아서 슬쩍 넣어봤어요. 해당 내용을 함께 깊게 보는 것도 재밌을 것 같고, 해당 내용을 함께 보지 않더라도 복제를 사용하는 예와 함께 복제를 사용했을 때 발생할 수 있는 문제점이나 주의점에 대해서 간단히 얘기해보는 시간 정도만 갖더라도 좋을 것 같아요.

**Comment by im-gnar** [comment]
저도 크게 다르지 않은 것 같습니다.

4장. 아키텍처
5장. 트랜잭션과 잠금
8장. 인덱스
9장. 옵티마이저와 힌트
10장. 실행 계획
11장. 쿼리 작성 및 최적화
12장. 확장 검색
13장. 파티션

정도 나오는 것 같은데요,
이번에 타회사에서 팀 면접관으로 간간히 들어가시는 중니어분이랑 얘기할 일이 있었는데 본인은 기술질문할 때 1차 필터링으로 인덱스 먼저 물어본다고 하더라구요
관련해서 나와야하는게 인덱스+옵티마이저+실행계획 정도인듯 해 해당 파트는 한번쯤 보고 넘어가면 좋을것같습니다!
(저는 RDB 안쓴지가 워낙 오래돼서 잘은 모르겟지만 ㅎㅎ;;)

**Comment by Deserve82** [comment]
저는 개인적으로 **실행계획**, **데이터 타입**, **스토어드 프로그램**, **복제**도 추가 되었으면 합니다. 

**데이터 타입**과 **실행 계획**도 어떻게 보면 최적화랑 밀접한 관련이 있다고 생각합니다. 

**스토어드 프로그램**은 많은 레거시들이 SP 로 되어 있는 부분들이 많아서 SP 부분도 일하면서 무조건 마주칠 거 같아서 추가했으면 좋겠습니다. 양이 너무 많다면 최소 스토어드 프로시저만 확인 및 실습 해도 될 거 같습니다.

 **복제** 같은 경우에는 추후에 대규모 프로젝트 아키텍처를 구성할 때에 사실 피할 수 없는 부분이라고 생각이 되어서 했으면 합니다. 

4장. 아키텍처
5장. 트랜잭션과 잠금
8장. 인덱스
9장. 옵티마이저와 힌트
10장. 실행 계획

11장. 쿼리 작성 및 최적화
12장. 확장 검색
13장. 파티션
14장. 스토어드 프로그램
15장. 데이터 타입
16장. 복제
18장. Performance 스키마 & Sys 스키마

**Comment by ruthetum** [comment]
resolve by https://github.com/Effective-Java-Camp/real-my-sql/commit/881b823be60d4f3e8832d372864f46b581240d2e
